name: Port Shader

on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get issue information
        uses: github.actions/issue@v1
        id: issue
        with:
          issue-number: ${{ github.event.issue.number }}

      - name: Download file from issue
        uses: actions/download-artifact@v2
        with:
          name: file-from-issue
          path: ${{ github.event.issue.body }}

      - name: Use file from issue
        run: |
          # Sử dụng file từ issue tại đây
          cd ${{ steps.issue.outputs.file-path }}"
          ls
