name: Shader Port
on:
  issues:
    types: labeled

jobs:
  get-pack-info:
    runs-on: ubuntu-latest
    permissions: 
      issues: read
    timeout-minutes: 2
    outputs:
      pack_url: ${{ steps.organize-inputs.outputs.PACK_URL }}

    steps:
      - name: Issue Forms Body Parser
        id: parse-issue
        uses: zentered/issue-forms-body-parser@v1.5.1
      - name: Organize Inputs
        id: organize-inputs
        run: |
          echo ${{ toJSON(steps.parse-issue.outputs.data) }} | jq '
          def test_input($input; $default):
          if ($input == "*No response*" or $input == "None") then $default else ($input | tostring | gsub("\\\\";""))  end;
          {
            "pack_url": .["shader-pack-direct-download-url"].text[1:-1],
          }' > inputs.json
          echo "PACK_URL=$(jq -r '.pack_url' inputs.json)" >> $GITHUB_OUTPUT

  port-shader:
    runs-on: ubuntu-latest
    needs: get-pack-info
    permissions: 
      contents: read
    timeout-minutes: 90
    outputs:
      run_id: ${{ steps.get-pack-info.outputs.pack_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          wget https://github.com/mcbegamerxx954/material-updater/releases/download/v0.1.11-hotfix2/material-updater-x86_64-unknown-linux-gnu.tar.gz
          tar xvzf material-updater-x86_64-unknown-linux-gnu.tar.gz
          mkdir ported

      - name: Port Shader
        id: port-shader
        continue-on-error: false
        env: 
          PACK_URL: ${{ needs.get-pack-info.outputs.pack_url }}

        run: |
          ./material-updater -t v1-21-20 -o ported.zip "${PACK_URL}"
          zip -T ported.zip
          ls
      - name: Upload ported shader pack
        uses: actions/upload-artifact@v4
        with:
          name: Pack Files
          path: ported
  post-result:
    runs-on: ubuntu-latest
    needs: convert-pack
    timeout-minutes: 2
    permissions: 
      issues: write
    steps:
      - name: Post Result
        id: post-result
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## :sparkles: The run has finished! :sparkles:
            - Download the pack files from the [action run][1] page. :arrow_double_down:
            - Upload the resource pack `geyser_resources.mcpack` to the `packs` folder of your Geyser folder. :file_folder:
            - Upload the mappings file `geyser_mappings.json` to the `custom_mappings` folder of your Geyser folder. :page_with_curl:

            If you notice issues with the converted files, please refer to the action log for errors and open a bug report if you believe there is an issue with the converter. This issue will be closed automatically.

            [1]: https://github.com/Kas-tle/java2bedrock.sh/actions/runs/${{ github.run_id}}
          reactions: 'rocket'
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
  conversion-failed:
    runs-on: ubuntu-latest
    needs: [get-pack-info, convert-pack, post-result]
    if: always() && (needs.get-pack-info.result == 'failure' || needs.convert-pack.result == 'failure' || needs.convert-pack.result == 'post-result')
    timeout-minutes: 2
    permissions: 
      issues: write
    steps:
      - name: Post Result
        id: post-result
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## :stop_sign: The run has failed :stop_sign:
            - Check the [action run][1] page for errors. :clipboard:
            - Status by job:
              - Get Pack Info: *${{ needs.get-pack-info.result }}*
              - Convert Pack: *${{ needs.convert-pack.result }}*
              - Post Result: *${{ needs.post-result.result }}*

            If you believe this is an issue with the converter. please open a bug report. This issue will be closed automatically.

            [1]: https://github.com/Kas-tle/java2bedrock.sh/actions/runs/${{ github.run_id}}
          reactions: 'x'
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}